export const GET_TECHNOLOGIES = "GET_TECHNOLOGIES";
export const GET_TECHNOLOGIE = "GET_TECHNOLOGIE";
export const ADD_TECHNOLOGIE = "ADD_TECHNOLOGIE";
export const DELETE_TECHNOLOGIE = "DELETE_TECHNOLOGIE";
export const EDIT_TECHNOLOGIE = "EDIT_TECHNOLOGIE";
