# Generated by Django 3.1.7 on 2021-10-13 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologieList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=255)),
                ('technologie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technologies.technologie')),
            ],
        ),
    ]
