# Generated by Django 3.1.7 on 2021-10-11 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0002_agregat_machine_powerunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quatity', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technologies.machine')),
            ],
        ),
    ]
