# Generated by Django 3.1.7 on 2021-10-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0002_technologielist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technologielist',
            old_name='operation',
            new_name='title',
        ),
        migrations.AddField(
            model_name='technologielist',
            name='operations',
            field=models.ManyToManyField(blank=True, to='technologies.Operation'),
        ),
    ]
