# Generated by Django 3.1.7 on 2021-10-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0003_auto_20211013_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologielist',
            name='operations',
        ),
        migrations.AddField(
            model_name='technologielist',
            name='agregats',
            field=models.ManyToManyField(blank=True, to='technologies.Agregat'),
        ),
    ]
