# Generated by Django 3.1.7 on 2021-04-08 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0003_auto_20210408_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
