# Generated by Django 3.1.7 on 2021-10-11 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0003_machineblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineblock',
            name='quatity',
        ),
    ]
