# Generated by Django 3.1.7 on 2021-10-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0004_remove_machineblock_quatity'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineblock',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
