# Generated by Django 3.1.7 on 2021-04-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0004_technologie_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
