# Generated by Django 3.1.7 on 2021-10-13 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0004_auto_20211013_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineblock',
            name='operationtype',
        ),
        migrations.AddField(
            model_name='machineblock',
            name='operationtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='technologies.operationtype'),
        ),
    ]
