# Generated by Django 3.1.7 on 2021-10-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0005_operation_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('value', models.FloatField(default=0.0)),
                ('od_vymiru', models.CharField(max_length=10)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='operation',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
