# Generated by Django 3.1.7 on 2021-10-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0005_auto_20211013_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerunit',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='powerunit',
            name='weigth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='powerunit',
            name='years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
