# Generated by Django 2.2.20 on 2021-10-12 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0006_agregat_machineblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregat',
            name='machine',
            field=models.ManyToManyField(null=True, to='technologies.Machine'),
        ),
        migrations.AlterField(
            model_name='agregat',
            name='machineblock',
            field=models.ManyToManyField(null=True, to='technologies.MachineBlock'),
        ),
        migrations.AlterField(
            model_name='agregat',
            name='powerunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='technologies.PowerUnit'),
        ),
    ]
