# Generated by Django 3.1.7 on 2021-10-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0006_auto_20211013_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologielist',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
