# Generated by Django 2.2.20 on 2021-10-12 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0007_auto_20211012_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregat',
            name='machine',
            field=models.ManyToManyField(blank=True, null=True, to='technologies.Machine'),
        ),
        migrations.AlterField(
            model_name='agregat',
            name='machineblock',
            field=models.ManyToManyField(blank=True, null=True, to='technologies.MachineBlock'),
        ),
        migrations.AlterField(
            model_name='agregat',
            name='powerunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='technologies.PowerUnit'),
        ),
    ]
