# Generated by Django 3.1.7 on 2021-10-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0007_technologielist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologielist',
            name='activated',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='technologielist',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
