# Generated by Django 2.2.20 on 2021-10-12 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0008_auto_20211012_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='agregats',
            field=models.ManyToManyField(blank=True, null=True, to='technologies.Agregat'),
        ),
        migrations.AlterField(
            model_name='agregat',
            name='machine',
            field=models.ManyToManyField(to='technologies.Machine'),
        ),
        migrations.AlterField(
            model_name='agregat',
            name='machineblock',
            field=models.ManyToManyField(to='technologies.MachineBlock'),
        ),
        migrations.AlterField(
            model_name='agregat',
            name='powerunit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technologies.PowerUnit'),
        ),
    ]
