# Generated by Django 2.2.20 on 2021-10-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0010_auto_20211012_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregat',
            name='machineblock',
            field=models.ManyToManyField(blank=True, null=True, to='technologies.MachineBlock'),
        ),
    ]
