# Generated by Django 2.2.20 on 2021-10-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0011_auto_20211012_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregat',
            name='machine',
            field=models.ManyToManyField(blank=True, null=True, to='technologies.Machine'),
        ),
    ]
