# Generated by Django 2.2.20 on 2021-10-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0012_auto_20211012_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
        ),
    ]
