# Generated by Django 2.2.20 on 2021-10-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0013_operationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='operation',
            field=models.ManyToManyField(blank=True, null=True, to='technologies.OperationType'),
        ),
    ]
