# Generated by Django 2.2.20 on 2021-10-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0014_operation_operation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='operation',
            new_name='operationtype',
        ),
    ]
