# Generated by Django 3.1.7 on 2021-10-12 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0015_auto_20211012_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregat',
            name='machine',
            field=models.ManyToManyField(blank=True, to='technologies.Machine'),
        ),
        migrations.AlterField(
            model_name='agregat',
            name='machineblock',
            field=models.ManyToManyField(blank=True, to='technologies.MachineBlock'),
        ),
        migrations.AlterField(
            model_name='agregat',
            name='powerunit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='technologies.powerunit'),
        ),
        migrations.AlterField(
            model_name='machineblock',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='agregats',
            field=models.ManyToManyField(blank=True, to='technologies.Agregat'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operationtype',
            field=models.ManyToManyField(blank=True, to='technologies.OperationType'),
        ),
    ]
