# Generated by Django 3.1.7 on 2021-10-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0016_auto_20211012_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='agregat',
            name='operationtype',
            field=models.ManyToManyField(blank=True, to='technologies.OperationType'),
        ),
    ]
