# Generated by Django 3.1.7 on 2021-10-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0017_agregat_operationtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineblock',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='machineblock',
            name='quantity',
        ),
        migrations.AddField(
            model_name='machine',
            name='operationtype',
            field=models.ManyToManyField(blank=True, to='technologies.OperationType'),
        ),
        migrations.AddField(
            model_name='machineblock',
            name='operationtype',
            field=models.ManyToManyField(blank=True, to='technologies.OperationType'),
        ),
    ]
