# Generated by Django 3.1.7 on 2021-10-12 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0018_auto_20211012_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineblock',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='technologies.machine'),
        ),
        migrations.AddField(
            model_name='machineblock',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
