# Generated by Django 3.1.7 on 2021-10-12 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
        ('technologies', '0020_machine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerunit',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.photo'),
        ),
    ]
